title: Résumé

footer:
  enable: true # decide where you want to show  your footer
  copyright:  # customize your copyright in footer, e.g. © 2019-2020 Zhiwei Li
    startYear: 2021
    currentYear: 2022
    author: Ziyue Zhang
    link: https://github.com/inkfin
    beian: 


################################
#     Write your resume Here   #
################################
resume:
  name: Ziyue Zhang
  #jobtitle: Your Job Title
  portrait: img/avatar.jpg # author's portrait
  contact:
    - icon: fa-envelope
      text: inkfinite@qq.com
    - icon: fa-phone-square
      text: +86 13554990010
    #- icon: fa-globe
      #text: your-website.com
      #link: https://github.com/mtics/hexo-mtics-resume
    - icon: fa-github
      text: MyGithub
      link: https://github.com/inkfin
  education:
    - university: Southern University of Science and Technology
      duration: Sep 2019 - Jun 2023
      location: Shenzhen, China
      major: Computer Science and Engineering
    #- university: Your Second University
      #duration: Aug 2007 - Jun 2011
      #location: Ut enim ad minim veniam
      #major: Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat
  experience:
    - title: Job Title 1
      duration: Apr 2016 - Now
      company: Your 1st, Inc.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    - title: Job Title 2
      duration: Apr 2013 - Mar 2016
      company: Your 2nd, Inc.
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    - title: Job Title 3
      duration: Dec 2011 - Mar 2012
      company: Your 3rd Co, Ltd.
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  projects:
    - name: Project Name 1
      description: Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Contributor.
    - name: Project Name 2
      description: Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      contribution: Creator and maintainer.
  skills:
    - title: Skill Group 1
      items: Lorem, Ipsum, Dolor, Sit, Amet
    - title: Skill Group 2
      items: Consectetur, Adipiscing, Elit
    - title: Skill Group 3
      items: Sed do, Eiusmod, Tempor, Incididunt
